[package]
name = "docker-yaml-build"
version = "0.1.0"
authors = ["Janito Vaqueiro Ferreira Filho <janito@mullvad.net>"]
edition = "2018"

[dependencies]
failure = "0.1"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
structopt = "0.2"
